---
- name: Apt playbook
  hosts: vagrant,localhost,all
  become: true
  #become_user: vagrant
  gather_facts: false

  tasks:
    - name: Apt packages installation
      ansible.builtin.package:
        name: 
          - "nginx"
        state: latest
        update_cache: true
