---
- name: Packages installation playbook
  hosts: "{{ hosts }}"
  become: true
  become_method: su
  become_user: root
  become_exe: sudo su -
  gather_facts: false

  tasks:
    - name: Apt packages installation
      ansible.builtin.package:
        name: 
          - nginx
          - php
          - php-fpm
          - mysql-server
          - mysql-client
        state: latest
        update_cache: true
