---
- name: Demo ping playbook
  hosts: "{{ hosts }}"
  become: true
  become_method: su
  become_user: root
  become_exe: sudo su -
  gather_facts: false

  tasks:
    - name: Ping server
      ping:
      when: hosts is defined 