---
- name: Demo shell playbook
  hosts: vagrant,localhost,all
  become: true
  become_method: su
  gather_facts: false

  tasks:
    - name: Shell command execution
      shell: "{{ shell_command }}"
